config/routes.rb
Rails.application.routes.draw do
  
  get "reservations/home" => "reservations#home"

  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  
  
  get "rooms/index" => "rooms#index"
  get "rooms/new" => "rooms#new"
  get "rooms/search" => "rooms#search"
  get "rooms/:id/detail" => "rooms#detail"
  post "rooms/create" => "rooms#create" 
 
  get "bookings/index" => "bookings#index"
  post "bookings/confirm" => "bookings#confirm"
  post "bookings/reconfirm" => "bookings#reconfirm"
  
  resources :users
  resources :bookings
  
  root "reservations#home"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
  validates :user_id, :room_id, :check_in, :check_out, :num_guests, presence: true
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  belongs_to :user
  has_many :booking
  
  validates :name, :room_comment, :room_charge, :address, :room_image, :user_id, presence: true
  
  def user
    return User.find_by(id: self.user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :room, dependent: :destroy
  has_many :booking, dependent: :destroy
  
  def rooms
    return Room.where(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user
  before_action :set_search

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
  
  def forbit_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/users/show")
    end
  end

  def set_search
    @search = Room.ransack(params[:q])
    @rooms = @search.result(distinct: true)
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  before_action :authenticate_user, only:[:index, :confirm]
  
  def index
    @current_user = User.find_by(id: session[:user_id])
    @bookings = Booking.where(user_id: @current_user.id)
  end
  
  def confirm
    @room = params[:room_id]
    @room = Room.find(@room)
    @booking = Booking.new(
      user_id: @current_user.id,
      room_id: params[:room_id],
      check_in: params[:check_in],
      check_out: params[:check_out],
      num_guests: params[:num_guests]
    )
    session[:booking] = @booking
    if @booking.invalid?
      redirect_to "/rooms/#{@room.id}/detail"
    else
      @booking.ttl_charge = (@booking.check_out - @booking.check_in).to_i * @booking.num_guests * @room.room_charge
    end
  end
  
  def reconfirm
    @booking = Booking.create!(session[:booking])
    @room = Room.find_by(id: params[:room_id])
    @booking.room_image = @room.room_image
		@booking.room_name = @room.name
		@booking.room_comment = @room.room_comment
    if params[:back]
      redirect_to "/rooms/#{@room.id}/detail"
    else @booking.save!
      session.delete(:booking)
      flash[:notice] = "予約が完了しました"
      redirect_to "/bookings/#{@booking.id}"
    end
  end
  
  def show
    @room = Room.find_by(id: params[:room_id])
    @booking = Booking.find_by(id: params[:id])
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
 
  def home
    @user = User.find_by(id: params[:id])
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
 before_action :set_search
 before_action :authenticate_user, only:[:new, :create, :detail]

  def index
    @rooms = Room.all
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @current_user = User.find_by(id: session[:user_id])
    @room = Room.new(
      name: params[:name],
      room_comment: params[:room_comment],
      room_charge: params[:room_charge],
      address: params[:address],
      room_image: params[:room_image],
      user_id: @current_user.id
      )
    if @room.save
      @room.room_image = "#{@room.id}.jpg"
      room_image = params[:room_image]
      File.binwrite("public/room_images/#{@room.room_image}", room_image.read)
      flash[:notice] = "登録しました"
      redirect_to("/rooms/index")
    else
      flash[:notice] = "入力に誤りがあります"
      @name = params[:name]
      @room_comment = params[:room_comment]
      @rooom_charge = params[:room_charge]
      @address = params[:address]
      render "rooms/new"
    end
  end
  
  def search
    @room = Room.find_by(id: params[:id])
    @rooms_count = @rooms.count
  end
  
  def detail
    @room = Room.find_by(id: params[:id])
    @current_user = User.find_by(id: session[:user_id])
    @booking = Booking.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user, only:[:show, :edit, :update]
  before_action :forbit_login_user, only:[:new, :create, :login_form, :login]
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "アカウント登録完了しました"
      redirect_to("/users/#{@user.id}")
    else
      flash[:notice] = "入力に誤りがあります"
      @name = params[:name]
      @mail = params[:mail]
      render("users/new")
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.comment = params[:comment]
    if params[:user_image]
    @user.image_name = "#{@user.id}.jpg"
    user_image = params[:user_image]
    File.binwrite("public/user_images/#{@user.image_name}", user_image.read)
    end
    
    if @user.save
      flash[:notice] = "更新されました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
  
  def destroy
  end
  
  def login_form
  end
  
  def login
    @user = User.find_by(mail: params[:mail], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/reservations/home")
    else
      @error_message = "メールアドレスまたはパスワードに誤りがあります"
      @mail = params[:mail]
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[notice] = "ログアウトしました"
    redirect_to("/login")
  end
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "編集権限がありません"
      redirect_to("/reservations/home")
    end
  end
  
  private
  def user_params
    params.permit(:name, :mail, :password, image_name: "default_user.jpeg")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirm.html.erb
<div class="container booking-page">
  <div class="room-row">
    <div class="booking-create-grid adjust">
      <h4 class="booking-create-check">予約内容確認</h4>
      <h5 class="booking-create-charge">¥ <%= @room.room_charge %>/Day</h5>
      <div class="booking-create-data">
        <label>Check-in</label>
          <p class="form-control"><%= @booking.check_in.strftime('%Y年%-m月%-d日') %></p>
        <label>Check-out</label>
          <p class="form-control"><%= @booking.check_out.strftime('%Y年%-m月%-d日') %></p>
        <label>人数</label>
          <p class="form-control"><%= @booking.num_guests %>/名</p>
        <label>合計料金</label>
          <p class="form-control">¥ <%= @booking.ttl_charge %></p>
        <p>上記内容でよろしければ「予約」を押してください</p>
        <div class="submit">
          <%= form_with url: "/bookings/reconfirm", method: :post, local: true do |f| %>
            <%= f.hidden_field :check_in %>
            <%= f.hidden_field :check_out %>
            <%= f.hidden_field :num_guests %>
            <%= f.hidden_field :ttl_charge %>
            <%= hidden_field_tag :room_id, @room.id %>
            <%= f.submit "予約", class: 'btn btn-no3' %>
            <%= f.submit "ルーム詳細へ戻る", name: :back, class: 'btn btn-no3' %>
          <% end %>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="room-container">
  <h3 class="search-count">予約済みルーム一覧</h3>
   <table>
    <thead>
      <tr>
        <th scope="col">ルーム画像</th>
        <th scope="col">ルーム名</th>
        <th scope="col">ルーム紹介</th>
        <th scope="col">合計料金</th>
        <th scope="col">Check-in</th>
        <th scope="col">Check-out</th>
        <th scope="col">作成日</th>
      </tr>
    </thead>
    <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to image_tag("/room_images/#{booking.room_id}.jpg", class:"room-image"), "/rooms/#{booking.room_id}/detail" %></td>
        <td class="room-title"><%= link_to(booking.room_name, "/rooms/#{booking.room_id}/detail") %></td>
        <td><%= booking.room_comment %></td>
        <td>¥ <%= booking.ttl_charge %></td>
        <td><%= booking.check_in.strftime('%Y年%-m月%-d日') %></td>
        <td><%= booking.check_out.strftime('%Y年%-m月%-d日') %></td>
        <td><%= booking.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/show.html.erb
<div class="container-booking-page">
  <div class="room-row">
    <div class="reconfirm-view">
      <div class="booking-reconfirm-grid">
        <div class="booking-reconfirm-data">
          <div class="form-row">
            <label class="content-label">予約の部屋</label>
            <div class="content-data">
              <%= @booking.room_name %>
            </div>
          </div>
        </div>
        <div class="booking-reconfirm-data">
          <div class="form-row">
            <label class="content-label">Check-in</label>
            <div class="content-data">
              <%= @booking.check_in.strftime('%Y年%-m月%-d日') %>
            </div>
          </div>
        </div>
        <div class="booking-reconfirm-data">
          <div class="form-row">
            <label class="content-label">Check-out</label>
            <div class="content-data">
              <%= @booking.check_out.strftime('%Y年%-m月%-d日') %>
            </div>
          </div>
        </div>
        <div class="booking-reconfirm-data">
          <div class="form-row">
            <label class="content-label">合計料金</label>
            <div class="content-data">
              ¥ <%= @booking.ttl_charge %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>
  <header class="header">
    <div class="header-logo">
      <a href="/reservations/home">
        <img alt="サイトロゴ" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
      </a>
      <div class="header-search">
        <%= search_form_for @search, url: rooms_search_path do |f| %>
          <%= f.search_field :address_cont, class: "header-form-control", placeholder: "エリア" %>
          <i class="area-icon"></i>
          <%= f.search_field :address_or_name_cont, class: "header-form-control", placeholder: "キーワード" %>
          <i class="keyword-icon"></i>
          <%= f.submit "探す", class: "hidden-btn" %>
        <% end %>
      </div>
    </div>
    <div class="header-nav">
      <div class="nav-right-btn">
        <% @current_user = User.find_by(id: session[:user_id]) %>
        <% if @current_user %>
          <div class="nav-btn">
            <li><%= link_to(@current_user.name, "/users/#{@current_user.id}") %></li>
            <% if @current_user.image_name == nil %>
              <li><%= image_tag "/user_images/default_user.jpeg", id:"acdn-button", class:"account-img" %></li>
            <% else %>
              <li><%= image_tag "/user_images/#{@current_user.id}.jpg", id:"acdn-button", class:"account-img" %></li>
            <% end %>
          </div>
        <% else %>
          <a href="/login" class="btn btn-no1">ログイン</a>
          <a href="/users/new" class="btn btn-no2">新規登録</a>
        <% end %>
      </div>
    </div>
  </header>
  
  <% if @current_user %>
    <ul class="header-nav-menu" id="acdn-menu">
      <li class="devide-line">|</li>
      <li class="nav-menu"><%= link_to("ルーム登録", "/rooms/new") %></li>
      <li class="devide-line">|</li>
      <li class="nav-menu"><%= link_to("予約済みルーム一覧", "/bookings/index") %></li>
      <li class="devide-line">|</li>
      <li class="nav-menu"><%= link_to("登録済みルーム一覧", "/rooms/index") %></li>
      <li class="devide-line">|</li>
      <li class="nav-menu"><%= link_to("設定", "/users/#{@current_user.id}") %></li>
      <li class="devide-line">|</li>
      <li class="nav-menu"><%= link_to("ログアウト", "/logout", method: :post) %></li>
      <li class="devide-line">|</li>
    </ul>
  <% end %>

  <%if  flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
  
  <footer class="footer">
    <p>© 2020 POTEPAN.INC.</p>
  </footer>
</html>

app/views/reservations/home.html.erb
<div class="main">
  <div class="container">
    <div class="content-width">
      <div class="form-frame">
        <div class="form-area">
          <p class="form-title">Potepan Shareで未体験の旅をしよう。</p>
          <p class="area">エリア</p>
          <div class="search-form">
            <%= search_form_for @search, url: rooms_search_path do |f| %>
              <%= f.search_field :address_cont, class: "form-control", placeholder: "東京" %>
              <%= f.submit "探す", class: 'btn btn-no3' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="recommend-frame">
      <p class="recommend-title">おすすめの体験エリア</p>
      <div class="recommend-grid">
        <div class="recommend-content">
          <div class="recommend-image">
            <a href="https://ec504434fc0c4ea6bb2363d07891dcb6.vfs.cloud9.ap-northeast-1.amazonaws.com/rooms/search?q%5Baddress_cont%5D=%E6%9D%B1%E4%BA%AC&commit=%E6%8E%A2%E3%81%99">
              <img class="recommend-icon" src="/recommend_icons/Tokyo.jpeg" alt="東京">
            </a>
          </div>
          <div class="recommend-info">
            <b>東京</b>
            <p>車で30分</p>
          </div>
        </div>
        <div class="recommend-content">
          <div class="recommend-image">
            <a href="https://ec504434fc0c4ea6bb2363d07891dcb6.vfs.cloud9.ap-northeast-1.amazonaws.com/rooms/search?q%5Baddress_cont%5D=%E7%A5%9E%E5%A5%88%E5%B7%9D&commit=%E6%8E%A2%E3%81%99">
              <img class="recommend-icon" src="/recommend_icons/Kanagawa.jpeg" alt="神奈川">
            </a>
          </div>
          <div class="recommend-info">
            <b>神奈川</b>
            <p>車で40分</p>
          </div>
        </div>
        <div class="recommend-content">
          <div class="recommend-image">
            <a href="https://ec504434fc0c4ea6bb2363d07891dcb6.vfs.cloud9.ap-northeast-1.amazonaws.com/rooms/search?q%5Baddress_cont%5D=%E9%95%B7%E9%87%8E&commit=%E6%8E%A2%E3%81%99">
              <img class="recommend-icon" src="/recommend_icons/Nagano.jpeg" alt="長野">
            </a>
          </div>
          <div class="recommend-info">
            <b>長野</b>
            <p>車で2時間</p>
          </div>
        </div>
        <div class="recommend-content">
          <div class="recommend-image">
            <a href="https://ec504434fc0c4ea6bb2363d07891dcb6.vfs.cloud9.ap-northeast-1.amazonaws.com/rooms/search?q%5Baddress_cont%5D=%E4%BA%AC%E9%83%BD%E5%BA%9C&commit=%E6%8E%A2%E3%81%99">
              <img class="recommend-icon" src="/recommend_icons/Kyoto.jpeg" alt="京都">
            </a>
          </div>
          <div class="recommend-info">
            <b>京都</b>
            <p>車で6時間30分</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/rooms/detail.html.erb
<div class="room-container">
  <div class="room-row devide">
      <div class="content-left">
        <img src="<%= "/room_images/#{@room.id}.jpg" %>" class="room-detail-image">
        <div class="room-detail">
          <div class="account-img">
          <% if @current_user %>
            <% if @current_user.image_name == nil %>
              <%= image_tag "/user_images/default_user.jpeg", id:"acdn-button", class:"account-img" %>
            <% else %>
              <%= image_tag "/user_images/#{@current_user.id}.jpg", id:"acdn-button", class:"account-img" %>
            <% end %>
          <% end %>
          </div>
          <div class="room-detail-profile">
            <p class="room-detail-title"><%= @room.name %></p>
            <p class="room-detail-address"><%= @room.address %></p>
          </div>
        </div>
        <p class="room-detail-comment"><%= @room.room_comment %></p>
      </div>
      <div class="content-right">
        <div class="room-booking-grid">
          <h5 class="room-detail-charge">¥ <%= @room.room_charge %>/Day</h5>
          <div class="room-booking-data">
            <%= form_with url: "/bookings/confirm", method: :post, local: true do |b| %>
              <label>Check-in</label>
                <%= b.date_field :check_in, class: 'form-control', placeholder: "日程を追加" %>
              <label>Check-out</label>
                <%= b.date_field :check_out, class: 'form-control', placeholder: "日程を追加" %>
              <label>人数</label>
                <%= b.text_field :num_guests, class: 'form-control', placeholder: "ご利用人数を入力" %>
              <div class="submit">
                <%= b.submit "確認", class: 'btn btn-no3' %>
              </div>
                <%= hidden_field_tag :room_id, @room.id %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="room-container">
  <h3 class="search-count">登録済みルーム一覧</h3>
   <table>
    <thead>
      <tr>
        <th scope="col">ルーム画像</th>
        <th scope="col">ルーム名</th>
        <th scope="col">ルーム紹介</th>
        <th scope="col">料金</th>
        <th scope="col">作成日</th>
      </tr>
    </thead>
    <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to image_tag("/room_images/#{room.id}.jpg", class:"room-image"), "/rooms/#{room.id}/detail" %></td>
        <td class="room-title"><%= link_to(room.name, "/rooms/#{room.id}/detail") %></td>
        <td><%= room.room_comment %></td>
        <td>¥ <%= room.room_charge %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class="container">
  <div class="view-box">
    <div class="user-content">
      <h3>ルーム登録</h3>
    </div>
    <%= form_with url: "/rooms/create", method: :post, local: true do |room| %>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label">ルーム名</label>
        <div class="content-data">
          <%= room.text_field :name, value: @name, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label">ルームの説明</label>
        <div class="content-data">
          <%= room.text_area :room_comment, value: @room_comment, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label">1泊の料金</label>
        <div class="content-data">
          <%= room.text_field :room_charge, value: @room_charge, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label">住所</label>
        <div class="content-data">
          <%= room.text_field :address, value: @address, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label">ルーム画像</label>
        <div class="content-data">
          <%= room.file_field :room_image %>
        </div>
      </div>
    </div>
    <div class="submit">
      <%= room.submit "登録", class: 'btn btn-no4' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="room-container">
  <h3 class="search-count">検索結果:<%= @rooms_count %>件</h3>
  <div class="room-row">
    <% @rooms.each do |room| %>
    <div class="room-frame">
      <div class="room-inner">
        <%= link_to image_tag("/room_images/#{room.id}.jpg", class: "room-image"), "/rooms/#{room.id}/detail" %>
        <div class="room-info">
          <div class="room-title">
            <%= link_to(room.name, "/rooms/#{room.id}/detail") %>
          </div>
          <div class="room-address">
            <%= room.address %>
          </div>
          <div class="room-price">
            ¥ <%= room.room_charge %>/Day
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-profile">
  <div class="user-row">
    <ul>
      <li>
        <%= link_to("アカウント", "/users/#{@user.id}") %>
      </li>
      <li class="selected-line">
        <%= link_to("プロフィール", "/users/#{@user.id}/edit") %>
      </li>
    </ul>
  </div>
  <%= form_with url: "/users/#{@user.id}/update" do |user| %>
  <div class="user-account-view">
    <div class="view-box">
      <div class="user-content">
        <div class="form-row">
         <h3>プロフィール</h3>
        </div>
      </div>
      <div class="user-content">
        <div class="form-row">
          <div class="icon-box">
            <%= image_tag "/user_images/#{@user.id}.jpg", class:"account-img" %>
          </div>
        </div>
      </div>
      <div class="user-content">
        <div class="form-row">
          <label class="content-label must">アイコン画像</label>
          <div class="content-data">
            <%= user.file_field :user_image %>
          </div>
        </div>
      </div>
      <div class="user-content">
        <div class="form-row">
          <label class="content-label must">ユーザー名</label>
          <div class="content-data">
            <%= user.text_field :name, value: @user.name, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="user-content">
        <div class="form-row">
          <label class="content-label must">自己紹介</label>
          <div class="content-data">
            <%= user.text_area :comment, value: @user.comment, class: "form-control",  placeholder: "自己紹介を入力" %>
          </div>
        </div>
      </div>
      <div class="submit">
        <%= user.submit "更新", class: 'btn btn-no4' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login_form.html.erb
<% if @error_message %>
  <div class="error_message">
    <%= @error_message %>
  </div>
<% end %>

<div class="container">
  <div class="container-frame">
    <div class="container-inner">
      <h3 class="title">ログイン</h3>
      <%= form_with url: "/login" do |user| %>
        <div>
          <%= user.email_field :mail, value: @mail, class: "form-control", placeholder: "メールアドレス" %>
        </div>
        <div>
          <%= user.password_field :password, class: "form-control", placeholder: "パスワード" %>
        </div>
        <div class="submit">
          <%= user.submit "ログイン", class: 'btn btn-no6' %>
        </div>
      <% end %>
        <div class="submit">
          <%= link_to("新規登録", "/users/new", class: 'btn btn-no7') %>
        </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="view-box">
    <div class="user-content">
      <h3>ユーザー登録</h3>
    </div>
    <%= form_with url: "/users/create", method: :post, local: true do |user| %>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label must">ユーザー名</label>
        <div class="content-data">
          <%= user.text_field :name, value: @name, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label must">メールアドレス</label>
        <div class="content-data">
          <%= user.email_field :mail, value: @mail, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="user-content">
      <div class="form-row">
        <label class="content-label must">パスワード</label>
        <div class="content-data">
          <%= user.password_field :password, value: @user.password, class: "form-control", placeholder: "//8〜20字以内//" %>
        </div>
      </div>   
    </div>
    <div class="submit">
      <%= user.submit "アカウント作成", class: 'btn btn-no5' %>
    </div>
    <% end %>
    <div class="submit">
      <%= link_to("アカウントお持ちの方", "/login", class: 'btn btn-no4') %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-profile">
  <div class="user-row">
    <ul>
      <li class="selected-line">
        <%= link_to("アカウント", "/users/#{@user.id}") %>
      </li>
      <li>
        <%= link_to("プロフィール", "/users/#{@user.id}/edit") %>
      </li>
    </ul>
  </div>
  <div class="user-account-view">
    <div class="view-box">
      <div class="user-content">
        <h3>アカウント情報</h3>
      </div>
      <div class="user-content">
        <h5>ユーザー名</h5>
        <p><%= @user.name %></p>
      </div>
      <div class="user-content">
        <h5>メールアドレス</h5>
        <p><%= @user.mail %></p>
      </div>
      <div class="user-content">
        <h5>パスワード</h5>
        <p>********</p>
      </div>
      <div class="user-content">
        <% if @user.id == @current_user.id %>
          <p class="btn btn-no4"><%= link_to("編集", "/users/#{@user.id}/edit") %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>